import type { AuditLanguage, AuditLocation } from "./types.ts";
import type { Finding, SkillResult } from "../skills/types.ts";

export type AuditLocale = "en" | "he";

const HEBREW_RE = /[\u0590-\u05ff]/g;
const LATIN_RE = /[A-Za-z]/g;

export function auditLocaleForLanguage(language?: AuditLanguage): AuditLocale {
  return language === "he" || language === "mixed" ? "he" : "en";
}

export function auditLocaleForFinding(finding: Pick<Finding, "quote" | "explanationLanguage" | "rewrite">): AuditLocale {
  if (finding.explanationLanguage) return auditLocaleForLanguage(finding.explanationLanguage);
  const text = `${finding.quote ?? ""}\n${finding.rewrite ?? ""}`;
  const he = text.match(HEBREW_RE)?.length ?? 0;
  const latin = text.match(LATIN_RE)?.length ?? 0;
  return he > latin ? "he" : "en";
}

export const AUDIT_UI = {
  en: {
    apiCost: "API cost",
    chars: "chars",
    confidence: "Confidence",
    confidenceRationale: "Confidence rationale",
    documentQuote: "Document quote",
    evidence: "Evidence",
    factCheck: "Fact Check",
    factCheckGrounded: "Fact Check (Grounded)",
    footerDisclaimerIntro: "This report is provided for informational purposes only under the",
    footerDisclaimerOffline: "Results are generated by offline checks and may not be complete or accurate.",
    footerDisclaimerProviders: (providers: string) => `Results are generated by ${providers} and may not be complete or accurate.`,
    footerDisclaimerLiability: "The authors of CheckApp make no warranties and accept no liability for decisions made based on these results.",
    footerDisclaimerJudgement: "Always apply your own judgement before publishing.",
    approximateLocation: "Approximate location",
    location: "Location",
    grounding: "Grounding",
    matchedSource: "matched source",
    matchedSources: "matched sources",
    matchType: "Match type",
    notAssessed: "Not assessed",
    offlineChecks: "Offline checks",
    paragraph: "paragraph",
    plagiarismCheck: "Plagiarism Check",
    poweredBy: "Powered by",
    qualityReport: "Quality Report",
    date: "Date",
    score: "Score",
    totalCost: "Total Cost",
    findings: "Findings",
    provider: "Provider",
    summary: "Summary",
    readyForReview: "Ready for review",
    search: "Search",
    sentence: "sentence",
    source: "Source",
    suggestedRewrite: "Suggested rewrite",
    unsupported: "Unsupported",
    unverified: "Unverified",
    providerError: "Provider error",
    needsAttention: "Needs attention",
    doNotPublish: "Do not publish",
    words: "Words",
    checkedClaims: (checked: number, unsupported: number, unverified: number, provider?: string, skipped?: number, budgetStopReason?: string) =>
      `${checked} claims checked — ${unsupported} unsupported, ${unverified} unverified${skipped ? `, ${skipped} skipped${budgetStopReason ? ` by ${formatBudgetStopReason(budgetStopReason, "en")}` : ""}` : ""}${provider ? ` (via ${provider})` : ""}`,
  },
  he: {
    apiCost: "עלות API",
    chars: "תווים",
    confidence: "רמת ביטחון",
    confidenceRationale: "נימוק רמת הביטחון",
    documentQuote: "ציטוט מהמסמך",
    evidence: "ראיות",
    factCheck: "בדיקת עובדות",
    factCheckGrounded: "בדיקת עובדות מבוססת מקורות",
    footerDisclaimerIntro: "דוח זה ניתן למטרות מידע בלבד תחת",
    footerDisclaimerOffline: "התוצאות נוצרו על ידי בדיקות מקומיות ועלולות להיות לא מלאות או לא מדויקות.",
    footerDisclaimerProviders: (providers: string) => `התוצאות נוצרו על ידי ${providers} ועלולות להיות לא מלאות או לא מדויקות.`,
    footerDisclaimerLiability: "יוצרי CheckApp אינם נותנים אחריות ואינם אחראים להחלטות שמתקבלות על סמך התוצאות.",
    footerDisclaimerJudgement: "יש להפעיל שיקול דעת עצמאי לפני פרסום.",
    approximateLocation: "מיקום משוער",
    location: "מיקום",
    grounding: "ביסוס מקור",
    matchedSource: "מקור תואם",
    matchedSources: "מקורות תואמים",
    matchType: "סוג התאמה",
    notAssessed: "לא נבדק",
    offlineChecks: "בדיקות מקומיות",
    paragraph: "פסקה",
    plagiarismCheck: "בדיקת מקוריות",
    poweredBy: "מופעל על ידי",
    qualityReport: "דוח איכות",
    date: "תאריך",
    score: "ציון",
    totalCost: "עלות כוללת",
    findings: "ממצאים",
    provider: "ספק",
    summary: "סיכום",
    readyForReview: "מוכן לבדיקה",
    search: "חיפוש",
    sentence: "משפט",
    source: "מקור",
    suggestedRewrite: "ניסוח מוצע",
    unsupported: "לא נתמך",
    unverified: "לא אומת",
    providerError: "שגיאת ספק",
    needsAttention: "דורש טיפול",
    doNotPublish: "לא לפרסום",
    words: "מילים",
    checkedClaims: (checked: number, unsupported: number, unverified: number, provider?: string, skipped?: number, budgetStopReason?: string) =>
      `${checked} טענות נבדקו — ${unsupported} לא נתמכו, ${unverified} לא אומתו${skipped ? `, ${skipped} דולגו${budgetStopReason ? ` בגלל ${formatBudgetStopReason(budgetStopReason, "he")}` : ""}` : ""}${provider ? ` (באמצעות ${provider})` : ""}`,
  },
} as const;

export function formatBudgetStopReason(reason: string, locale: AuditLocale): string {
  if (locale === "he") {
    if (reason === "claim_cap") return "מכסת טענות";
    if (reason === "provider_call_budget") return "מכסת קריאות לספק";
    if (reason === "cost_budget") return "מכסת עלות";
    return reason.replace(/_/g, " ");
  }
  if (reason === "claim_cap") return "claim cap";
  if (reason === "provider_call_budget") return "provider-call budget";
  if (reason === "cost_budget") return "cost budget";
  return reason.replace(/_/g, " ");
}

export function localizedSkillName(result: Pick<SkillResult, "skillId" | "name">, locale: AuditLocale): string {
  const labels = AUDIT_UI[locale];
  if (result.skillId === "fact-check" || result.skillId === "factCheck") return labels.factCheck;
  if (result.skillId === "fact-check-grounded") return labels.factCheckGrounded;
  if (result.skillId === "plagiarism") return labels.plagiarismCheck;
  return result.name;
}

export function localizedVerdictLabel(verdict: string, locale: AuditLocale): string {
  const labels = AUDIT_UI[locale];
  if (verdict === "skipped") return labels.notAssessed;
  if (verdict === "pass") return labels.readyForReview;
  if (verdict === "warn") return labels.needsAttention;
  return labels.doNotPublish;
}

export function localizedConfidenceValue(confidence: string | undefined, locale: AuditLocale): string | undefined {
  if (!confidence) return undefined;
  if (locale === "he") {
    if (confidence === "high") return "גבוהה";
    if (confidence === "medium") return "בינונית";
    if (confidence === "low") return "נמוכה";
  }
  return confidence;
}

export function localizedFindingStatus(finding: Pick<Finding, "status" | "confidence">, locale: AuditLocale): string | undefined {
  const labels = AUDIT_UI[locale];
  if (finding.status === "unsupported") return labels.unsupported;
  if (finding.status === "unverified") return labels.unverified;
  if (finding.status === "provider_error") return labels.providerError;
  if (finding.status === "plagiarism_match") return labels.plagiarismCheck;
  if (finding.confidence) return `${labels.confidence}: ${finding.confidence}`;
  return undefined;
}

export function localizedFindingText(
  finding: Pick<Finding, "text" | "status" | "confidence" | "explanation" | "explanationLanguage">,
  locale: AuditLocale,
): string {
  const labels = AUDIT_UI[locale];
  if (locale === "he" && (finding.status === "unsupported" || finding.status === "unverified")) {
    const status = finding.status === "unsupported" ? labels.unsupported : labels.unverified;
    const confidence = finding.confidence ? ` (${labels.confidence}: ${localizedConfidenceValue(finding.confidence, locale)})` : "";
    const explanation = finding.explanation ? ` — ${finding.explanation}` : "";
    return `${status}${confidence}${explanation}`;
  }
  if (locale === "he" && finding.status === "provider_error") {
    const confidence = finding.confidence ? ` (${labels.confidence}: ${localizedConfidenceValue(finding.confidence, locale)})` : "";
    const explanation = finding.explanation ? ` — ${finding.explanation}` : "";
    return `${labels.providerError}${confidence}${explanation}`;
  }
  if (locale === "he" && finding.status === "plagiarism_match") {
    const confidence = finding.confidence ? ` (${labels.confidence}: ${localizedConfidenceValue(finding.confidence, locale)})` : "";
    const explanation = finding.explanation ? ` — ${finding.explanation}` : "";
    return `חשד להעתקה${confidence}${explanation}`;
  }
  return finding.text;
}

export function formatAuditLocation(location: AuditLocation, locale: AuditLocale): string {
  const labels = AUDIT_UI[locale];
  const locationLabel = location.matchQuality === "fuzzy" ? labels.approximateLocation : labels.location;
  const parts = [
    location.sectionTitle ?? location.sectionId,
    `${labels.paragraph} ${location.paragraphIndex + 1}`,
  ];
  if (typeof location.sentenceIndex === "number") parts.push(`${labels.sentence} ${location.sentenceIndex + 1}`);
  if (location.matchQuality !== "fuzzy" && typeof location.startOffset === "number" && typeof location.endOffset === "number") {
    parts.push(`${labels.chars} ${location.startOffset}-${location.endOffset}`);
  }
  return `${locationLabel}: ${parts.filter(Boolean).join(" · ")}`;
}
