import type { Config } from "./config.ts";

export interface AiSegment {
  text: string;
  aiScore: number; // 0.01–0.99
}

export interface AiDetectorResult {
  aiScore: number; // 0.01–0.99 global
  aiPct: number;   // rounded percentage for display
  verdict: "human" | "mixed" | "ai";
  topSegments: AiSegment[]; // top 3 highest-scoring segments
  error?: string;
}

const COPYSCAPE_API = "https://www.copyscape.com/api/";

// Thresholds — match industry conventions
const THRESHOLD_MIXED = 30; // 30%+ → mixed
const THRESHOLD_AI = 70;    // 70%+ → likely AI

export async function checkAiDetector(
  text: string,
  config: Config
): Promise<AiDetectorResult> {
  const body = new URLSearchParams({
    u: config.copyscapeUser,
    k: config.copyscapeKey,
    o: "aicheck",
    e: "UTF-8",
    f: "xml",
    t: text,
  });

  const response = await fetch(COPYSCAPE_API, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: body.toString(),
  });

  if (!response.ok) {
    throw new Error(`Copyscape AI detector error: HTTP ${response.status}`);
  }

  const xml = await response.text();
  return parseAiResponse(xml);
}

const GEMINI_AI_DETECT_BASE = "https://generativelanguage.googleapis.com/v1beta";
const GEMINI_AI_DETECT_MODEL = "gemini-3.1-pro-preview";

const AI_DETECTION_PROMPT = `You are an AI content detector. Analyze the following text and determine the probability that it was generated by an AI (LLM) rather than written by a human.

Respond ONLY with a valid JSON object in this exact format — no explanation, no markdown fences:
{
  "aiScore": <number 0.0–1.0>,
  "segments": [
    { "text": "<most AI-like sentence or phrase>", "aiScore": <number 0.0–1.0> }
  ]
}

Rules:
- aiScore: overall probability the text is AI-generated (0.0 = definitely human, 1.0 = definitely AI)
- segments: up to 3 most AI-like sentences/phrases with individual scores; empty array if all reads as human
- The text may be in any language — analyze regardless of language
- Only return the JSON object`;

interface GeminiAiDetectionResponse {
  aiScore: number;
  segments: Array<{ text: string; aiScore: number }>;
}

export async function checkAiDetectorGemini(
  text: string,
  config: Config
): Promise<AiDetectorResult> {
  const apiKey = config.providers?.["ai-detection"]?.apiKey ?? config.geminiApiKey;
  if (!apiKey) {
    return {
      aiScore: 0,
      aiPct: 0,
      verdict: "human",
      topSegments: [],
      error: "Gemini API key not configured — set GEMINI_API_KEY, config.geminiApiKey, or providers['ai-detection'].apiKey.",
    };
  }

  const url = `${GEMINI_AI_DETECT_BASE}/models/${GEMINI_AI_DETECT_MODEL}:generateContent`;

  let response: Response;
  try {
    response = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json", "x-goog-api-key": apiKey },
      body: JSON.stringify({
        contents: [{ parts: [{ text: `${AI_DETECTION_PROMPT}\n\nText to analyze:\n${text}` }] }],
        generationConfig: { temperature: 0, maxOutputTokens: 2048, responseMimeType: "application/json" },
      }),
    });
  } catch (err) {
    return {
      aiScore: 0, aiPct: 0, verdict: "human", topSegments: [],
      error: `Gemini AI detection network error: ${(err as Error).message}`,
    };
  }

  if (!response.ok) {
    return {
      aiScore: 0, aiPct: 0, verdict: "human", topSegments: [],
      error: `Gemini AI detection error: HTTP ${response.status}`,
    };
  }

  let data: { candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }> };
  try {
    data = await response.json() as typeof data;
  } catch {
    return {
      aiScore: 0, aiPct: 0, verdict: "human", topSegments: [],
      error: "Gemini AI detection: could not parse API response body",
    };
  }

  const rawText = data.candidates?.[0]?.content?.parts?.[0]?.text ?? "";

  let parsed: GeminiAiDetectionResponse;
  try {
    const cleaned = rawText.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "").trim();
    parsed = JSON.parse(cleaned) as GeminiAiDetectionResponse;
  } catch {
    return {
      aiScore: 0, aiPct: 0, verdict: "human", topSegments: [],
      error: `Gemini AI detection: could not parse response — ${rawText.slice(0, 120)}`,
    };
  }

  const aiScore = Math.min(1, Math.max(0, Number(parsed.aiScore) || 0));
  const aiPct = Math.round(aiScore * 100);
  const verdict: AiDetectorResult["verdict"] =
    aiPct >= THRESHOLD_AI ? "ai" : aiPct >= THRESHOLD_MIXED ? "mixed" : "human";

  const topSegments = (parsed.segments ?? [])
    .filter((s) => s && typeof s.text === "string" && typeof s.aiScore === "number")
    .map((s) => ({ text: s.text, aiScore: Math.min(1, Math.max(0, s.aiScore)) }))
    .sort((a, b) => b.aiScore - a.aiScore)
    .slice(0, 3)
    .filter((s) => s.aiScore >= 0.7);

  return { aiScore, aiPct, verdict, topSegments };
}

function parseAiResponse(xml: string): AiDetectorResult {
  const errorMatch = xml.match(/<error>([\s\S]*?)<\/error>/);
  if (errorMatch) {
    const msg = errorMatch[1].trim();
    if (msg.toLowerCase().includes("insufficient")) {
      return {
        aiScore: 0,
        aiPct: 0,
        verdict: "human",
        topSegments: [],
        error: "Copyscape credits insufficient — AI detection skipped.",
      };
    }
    throw new Error(`Copyscape AI detector error: ${msg}`);
  }

  const globalScore = parseFloat(
    xml.match(/<aiscore>([\d.]+)<\/aiscore>/)?.[1] ?? "0"
  );

  const segments: AiSegment[] = [];
  const segmentBlocks = [...xml.matchAll(/<segment>([\s\S]*?)<\/segment>/g)];
  for (const block of segmentBlocks) {
    const inner = block[1];
    const text = inner.match(/<text>([\s\S]*?)<\/text>/)?.[1]?.trim() ?? "";
    const score = parseFloat(
      inner.match(/<aiscore>([\d.]+)<\/aiscore>/)?.[1] ?? "0"
    );
    if (text) segments.push({ text, aiScore: score });
  }

  // Top 3 segments by AI score (only surface high-confidence ones)
  const topSegments = [...segments]
    .sort((a, b) => b.aiScore - a.aiScore)
    .slice(0, 3)
    .filter((s) => s.aiScore >= 0.7);

  const aiPct = Math.round(globalScore * 100);
  const verdict =
    aiPct >= THRESHOLD_AI
      ? "ai"
      : aiPct >= THRESHOLD_MIXED
      ? "mixed"
      : "human";

  return { aiScore: globalScore, aiPct, verdict, topSegments };
}
